local handler = require("handler")
local services = require("services")
local backendResponse = services.call("api:9000")
handler.writeStatus(200)
handler.writeBody("Backend: " .. backendResponse .. " frontend: Hello from lua!")
