secret_key: {{ .JWTSecret }}

# Public URL for Vue-powered UI.
site:
  scheme: 'http'
  host: 'localhost'

listen:
  # OTLP/gRPC API
  grpc: ':{{ .OtelGRPCPort }}'
  # OTLP/HTTP API and Uptrace API
  http: ':{{ .UptraceUIPort }}'

ch:
  # Connection string for ClickHouse database.
  # clickhouse://<user>:<password>@<host>:<port>/<database>?sslmode=disable
  dsn: 'clickhouse://default:@clickhouse:9000/uptrace?sslmode=disable'

retention:
  # Tell ClickHouse to delete data after 30 days.
  # Supports SQL interval syntax, for example, INTERVAL 30 DAY.
  ttl: 1 DAY

# Uncomment this section to require authentication.
#
# users:
#   - id: 1
#     username: uptrace
#     password: uptrace

projects:
  # First project is used for self-monitoring.
  - id: 1
    name: Uptrace
    token: project1_secret_token

  - id: 2
    name: LearnSystemDesign
    token: learn-system-design-secret-token

# Various limits we apply to queries on spans_index table.
#
# - https://clickhouse.com/docs/en/operations/settings/query-complexity/
# - https://clickhouse.com/docs/en/sql-reference/statements/select/sample/
ch_select_limits:
  # ClickHouse sampling is disabled by default,
  # because it only makes queries faster with big ClickHouse clusters
  sample_rows: 0
  max_rows_to_read: 12e6 # read at most 12 million rows
  max_bytes_to_read: 4e9 # read at most 4 gigabytes of data
